# Generated by Django 4.2.6 on 2023-12-09 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mobiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Price', models.CharField(max_length=50)),
                ('Company', models.CharField(max_length=200)),
            ],
        ),
    ]
