# Generated by Django 4.2.6 on 2023-12-11 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobiles',
            name='Image',
            field=models.ImageField(null=True, upload_to='Images'),
        ),
        migrations.AlterField(
            model_name='mobiles',
            name='Price',
            field=models.CharField(max_length=200),
        ),
    ]
